repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        name: lint
      - id: ruff
        name: sort imports
        args: [--select, I, --fix]
      - id: ruff-format
        name: format
