[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bmi_sdk"
version = "0.0.0"
dependencies = [
  "bmipy",
  "numpy"
]

[tool.setuptools]
package-dir={"bmi_sdk"="bmi_sdk"}

[tool.ruff]
exclude = [
    "./test*",
]
