name: PyTest Suite

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set UV_HTTP_TIMEOUT
      run: echo "UV_HTTP_TIMEOUT=600" >> $GITHUB_ENV

    - name: Build env and run tests
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt
        pytest
